Be more specific about the regex for version and name (#8)
Use the official [Semantic versioning](https://semver.org) regular
expression for the `version` part.
Make the `name` part only contain A-Z and a-z characters, but in a
randomized fashion.

Change the regex slightly to make `minor` and `patch` optional.

Also, add the README as the app description.

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -95,5 +95,15 @@ jobs:
         env:
           DOCKER_TEST_HOST: localhost
         run: |
-          ./.github/utils/docker_test.py run-tests
-          cat logs/dlite_entities_service.log
+          {
+            ./.github/utils/docker_test.py run-tests &&
+            cat logs/dlite_entities_service.log
+          } || {
+            echo "Failed! Here's the Docker logs for the service:" &&
+            docker logs entity-service &&
+
+            echo -e "\nAnd the service log:" &&
+            cat logs/dlite_entities_service.log &&
+
+            exit 1
+          }
