Report docker logs on failure to collect coverage

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -48,6 +48,7 @@ jobs:
       # These are used in the Dockerfile as well as in pytest
       ENTITIES_SERVICE_HOST: localhost
       ENTITIES_SERVICE_PORT: 8000
+      STOP_TIME: 3
 
     steps:
       - name: Checkout ${{ github.repository }}
@@ -109,7 +110,7 @@ jobs:
             --env ENTITIES_SERVICE_EXTERNAL_OAUTH \
             --env PORT=${ENTITIES_SERVICE_PORT} \
             --env RUN_TIME=40 \
-            --env STOP_TIME=3 \
+            --env STOP_TIME \
             --name "ds-entities-service" \
             --network "host" \
             --volume "${PWD}:/app" \
@@ -142,12 +143,22 @@ jobs:
           # stopping mechanism.
           touch stop_gunicorn
 
-          sleep 3  # Wait for the service to stop
+          sleep ${STOP_TIME}  # Wait for the service to stop
 
-          mv .coverage .coverage.pytest
-          coverage combine --data-file=.coverage.final --rcfile=pyproject.toml .coverage.pytest .coverage.docker
-          coverage xml --data-file=.coverage.final --rcfile=pyproject.toml -o coverage.xml
-          coverage report --data-file=.coverage.final --rcfile=pyproject.toml --show-missing --skip-covered --skip-empty
+          {
+            mv .coverage .coverage.pytest
+            coverage combine --data-file=.coverage.final --rcfile=pyproject.toml .coverage.pytest .coverage.docker
+            coverage xml --data-file=.coverage.final --rcfile=pyproject.toml -o coverage.xml
+            coverage report --data-file=.coverage.final --rcfile=pyproject.toml --show-missing --skip-covered --skip-empty
+          } || {
+            echo "Failed to collect coverage data! Here's the Docker logs for the service:" &&
+            docker logs ds-entities-service &&
+
+            echo -e "\nAnd the service log:" &&
+            cat logs/entities_service.log &&
+
+            exit 1
+          }
 
       - name: Upload coverage
         if: github.repository_owner == 'M-ERA-NET-MEDIATE'
